### ISSUE TITLE
build报错

### ISSUE THREAD

**Issue by peijian708** [jinpikaFE/vite-react-ts-admin#8]
build报错
![image](https://user-images.githubusercontent.com/347751/144780210-16f98311-a239-416d-b671-3a2a5b6d84de.png)

**Comment by jinxin1517** [comment]
我这边本地可以build，具体使用的哪个分支打包的。可以先删除node_modules，换成yarn试试。

**Comment by peijian708** [comment]
master 与 1.0都不行   我yarn install的  "skipLibCheck": true 可以了

**Comment by jinxin1517** [comment]
我是false的,最新的master是可以打包的，1.0出现了一样的问题。这个我刚开始打包好像也有这个问题，好像后来解决了，我排查下。

**Comment by jinxin1517** [comment]
只需要将build的 tsc命令删除即可，不进行ts检查。

**Comment by jinxin1517** [comment]
或者配置忽略node_modules文件的ts检查
